### ISSUE TITLE
Failed to compile using g++ 8.1

### ISSUE THREAD

**Issue by hirokiht** [obgm/libcoap-minimal#1]
https://github.com/obgm/libcoap-minimal/blob/5cfd14fa0b6e17dc9a9eddd8dd710a7596cbd4df/Makefile#L5

LDLIBS should be used instead of CXXFLAGS, using CXXFLAGS will result in the libraries added before the object files which leads to linker unable to find the corresponding libraries.

I also needed to change libcoap-2-openssl to libcoap-2 to find the library.

**Comment by obgm** [comment]
Thanks. Commit 1a5859f now resolves this.

(Regarding the name-change: You can invoke `make LIBCOAP=libcoap-2` if you happen to have a libcoap version that is built without DTLS support.)
