### ISSUE TITLE
Add hex data in minimal example

### ISSUE THREAD

**Issue by chandan-crsl** [obgm/libcoap-minimal#10]
I need help in adding hex data in minimal example. If I am sending it as normal payload then some bytes are missing/corrupted.

**Comment by obgm** [comment]
Do you have a trace and/or log output?  Do you use the client, the server, both?

**Comment by chandan-crsl** [comment]
> Do you have a trace and/or log output? Do you use the client, the server, both?

I am using both client and server, I am using libcoap-minimal code. 

At client side:
`v:1 t:CON c:PUT i:6c9c {} [ Uri-Path:\x00\x05Slick\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00LWFNGWp1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \xA2]\xEB\x09\xBA]\xEB\x09\xBA\x00\x00\x00mBIN\x00\x00\x00\x00\x00\x00 ]`

At server side:
uri_path.s `%00%05Slick%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00LWFNGWp1%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%00%20%A2%5D%EB%09%BA%5D%EB%09%BA%00%00%00mBIN%00%00%00%00%00%00`

When I try to print the hex value at server side, it is showing this:

`25 30 30 25 30 35 53 6c 69 63 6b 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30 25 30 30`

However, the actual output should be:

`00 05 53 6c 69 63 6b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 4c 57 46 4e 47 57 70 31 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 20 a2 5d eb 09 ba 5d eb 09 ba 00 00 00 6d 42 49 4e 00 00 00 00 00 00`

**Comment by mrdeep1** [comment]
Are you trying to send this as payload data, or as a path (as in /some/path/to/somewhere) ?

As per [RFC7252 6.5 Composing URIs from Options](https://datatracker.ietf.org/doc/html/rfc7252#section-6.5) step 6, the server side path is correctly being decoded and reported in` uri_path.s`.

See [coap_pdu_setup(3)](https://libcoap.net/doc/reference/develop/man_coap_pdu_setup.html) for information on how to add data to a CoAP request.

**Comment by chandan-crsl** [comment]
> Are you trying to send this as payload data, or as a path (as in /some/path/to/somewhere) ?
> 
> As per [RFC7252 6.5 Composing URIs from Options](https://datatracker.ietf.org/doc/html/rfc7252#section-6.5) step 6, the server side path is correctly being decoded and reported in` uri_path.s`.
> 
> See [coap_pdu_setup(3)](https://libcoap.net/doc/reference/develop/man_coap_pdu_setup.html) for information on how to add data to a CoAP request.

Thanks mate, it's working. I had added the payload and I am getting the data correctly at server side.

Thank you once again. I am closing this issue.
