### ISSUE TITLE
How to add dynamic handler at server side

### ISSUE THREAD

**Issue by chandan-crsl** [obgm/libcoap-minimal#7]
Hi all, 
Can anyone help me with deploying dynamic handler at the server.cc code. I am using functions from https://libcoap.net/doc/reference/4.2.0/resource_8c_source.html#l00334

I just want to check if I am going in the right direction.

**Comment by obgm** [comment]
Well, as stated in the README file, libcoap-minimal requires libcoap-3. Creating a dynamic handler with libcoap-2 is somewhat messy.

**Comment by chandan-crsl** [comment]
Closing this, as it has solved.
