### ISSUE TITLE
Issue with coap_resource_unknown_init

### ISSUE THREAD

**Issue by chandan-crsl** [obgm/libcoap-minimal#8]
I am facing issue with 
###  r = coap_resource_unknown_init(hnd_unknown_put); 

hnd_unknown_put is defined on the top, I am following the steps as given in 

https://libcoap.net/doc/reference/develop/man_coap_resource.html

in examples, dynamic set up
 for setting up dynamic handler at server side.

![image](https://user-images.githubusercontent.com/108401570/176436049-45416c61-6bf5-411e-b3c5-244c1f0c5df6.png)

Any help will be appreciated.

**Comment by obgm** [comment]
The error message gives a hint: The function you are passing to `coap_resource_unknown_init()` has the wrong signature. Maybe you are mixing libcoap versions (4.2.x vs. 4.3.x)?
