### ISSUE TITLE
Send response to client upon request under dynamic setup

### ISSUE THREAD

**Issue by chandan-crsl** [obgm/libcoap-minimal#9]
Hi All,

I was able to setup dynamic resource handling at server side. Now, I want to add response which can be sent to client. 

In libcoap-minimal/server.cc, this is the code sending response to client 

```
  resource = coap_resource_init(ruri, 0);
  coap_register_handler(resource, COAP_REQUEST_GET,
                        [](auto, auto,
                           const coap_pdu_t *request,
                           auto,
                           coap_pdu_t *response) {
                          coap_show_pdu(LOG_WARNING, request);
                          coap_pdu_set_code(response, COAP_RESPONSE_CODE_CONTENT);
                          coap_add_data(response, 5,
                                        (const uint8_t *)"world");
                          coap_show_pdu(LOG_WARNING, response);
                        });
  coap_add_resource(ctx, resource);
```

How can I use the same in dynamic resource? Looking forward for positive response from fellow developers.

**Comment by mrdeep1** [comment]
You can either just send back a response within the dynamic unknown handler, or create a new resource based on the uri received in the dynamic handler, register handlers against that new resource and add that resource to coap context.  Then call the just registered handler to send back the appropriate data.

**Comment by mrdeep1** [comment]
> I was able to setup dynamic resource handling at server side. 

@chandan-crsl Please close #7 and #8 now that you know how to set it up.

**Comment by chandan-crsl** [comment]
I am closing this, as it has solved.
